### PR TITLE
Resolves #1; Fixes style

### LINKED ISSUE #1: Design windowing interface

### PR DESCRIPTION
**Pull request by kelleyb**
Fixing style of main.c

### CODE REVIEW

**Comment by JohnBehnke** [comment]
Why are you pushing C code? This is a C++17 project.

**Comment by kelleyb** [comment]
Oh whoops. I'll fix that.

**Comment by JohnBehnke** [comment]
Yeah you are

**Comment by JohnBehnke** [comment]
Looks good to me.

**Pull request merged**
